### PR TITLE
Handle support of Ack msg in sleeping & waitForConnection state of Publisher FSM

### PR DESCRIPTION
**Pull request by jccimino**
We are getting this error from the triton digital library:

[ERROR] [01/06/2016 12:00:34.373] [instrumentation-enrichment-akka.actor.default-dispatcher-18] [akka://instrumentation-enrichment/user/datadog-connection-1] Ack(ArrayBuffer(Metric(datadog.publication.m1,DoubleValue(0.057952403876142033),WrappedArray(),1452081633), Metric(java.heap.usage,LongValue(65124480),List(),1452081633), Metric(java.cpu.load,DoubleValue(0.006090928866652165),List(),1452081633)),4,akka.actor.LightArrayRevolverScheduler$TaskHolder@1b2a22b5) (of class com.tritondigital.counters.datadog.DatadogPublisher$Ack)
scala.MatchError: Ack(ArrayBuffer(Metric(datadog.publication.m1,DoubleValue(0.057952403876142033),WrappedArray(),1452081633), Metric(java.heap.usage,LongValue(65124480),List(),1452081633), Metric(java.cpu.load,DoubleValue(0.006090928866652165),List(),1452081633)),4,akka.actor.LightArrayRevolverScheduler$TaskHolder@1b2a22b5) (of class com.tritondigital.counters.datadog.DatadogPublisher$Ack)
at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:248)
at scala.PartialFunction$$anon$1.apply(PartialFunction.scala:246)
at com.tritondigital.counters.datadog.DatadogPublisher$DatadogConnection$$anonfun$errorManagement$1.applyOrElse(DatadogPublisher.scala:120)
at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
at com.tritondigital.counters.datadog.DatadogPublisher$DatadogConnection$$anonfun$sleeping$1.applyOrElse(DatadogPublisher.scala:75)

It is due to the fact that in the DatadogPublisher, the DatadogConnection actor could have transitioned from sending state to sleeping state while some metrics were still being published or waiting for their Ack. The sleeping state must discard any "late" Ack of metrics. We think that we could have the same issue while being in waitForConnection.

### CODE REVIEW

**Comment by gbranchaudrubenovitch** [comment]
Thanks a lot for the contribution.

**Comment by jccimino** [comment]
Hi,
would it be possible to generate a new version based on this fix under maven central please ?
Current version is 1.0.1 from May-2015.
Would be really nice to have the 1.0.2 including the fix.
Thanks a lot.
/JC

**Comment by gbranchaudrubenovitch** [comment]
Hi, sorry about the delay.

The new v1.0.2 should be available from the repos in the next hours.

Thanks,

**Comment by jletroui** [comment]
Many thanks Gabriel!

**Pull request merged**
